version: '3'
services:
  db: 
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=profesoresacasa

  web:
    build: profesores_a_casa/.
    hostname: web
    expose: 
      - "8443"
    restart: unless-stopped
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/profesoresacasa
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    deploy:
      mode: replicated
      replicas: 2

  rabbitmq:
    image: rabbitmq

  servicio_correo:
    build: servicio_correo/.
    hostname: service
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    deploy:
      mode: replicated
      replicas: 2

  loadbalancer:
    image: haproxy:2.7.3
    ports:
      - "9443:443" # Only service that is exposed to the host is the lb
      - "9080:8080" # Haproxy Stats
      - "9090:80" # http (should not work)
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    restart: unless-stopped